# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-12 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_url',
            new_name='git_url',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=models.CharField(default='hello', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
