# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_auto_20180812_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.Occupation')),
            ],
        ),
    ]
