# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_remove_occupation_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.Position')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='In Progress', max_length=100),
            preserve_default=False,
        ),
    ]
