# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0006_auto_20180815_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
