# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-15 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0008_auto_20180815_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('paragraph', models.TextField(max_length=950)),
            ],
        ),
    ]
