# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-15 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0009_coverletterparagraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletterparagraph',
            name='topic',
        ),
        migrations.AddField(
            model_name='coverletterparagraph',
            name='paragraph_position',
            field=models.CharField(choices=[('Header', 'Header'), ('Introduction', 'Introduction'), ('Paragraph 1', 'Paragraph 1'), ('Paragraph 2', 'Paragraph 2'), ('Paragraph 3', 'Paragraph 3'), ('Conclusion', 'Conclusion'), ('Footer', 'Footer')], default='Header', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coverletterparagraph',
            name='type',
            field=models.CharField(choices=[('Project', 'Project'), ('Occupation', 'Occupation'), ('Course', 'Course')], default='Project', max_length=100),
            preserve_default=False,
        ),
    ]
