# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-15 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0010_auto_20180915_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletterparagraph',
            name='type',
            field=models.CharField(choices=[('Base', 'Base'), ('Project', 'Project'), ('Occupation', 'Occupation'), ('Course', 'Course')], max_length=100),
        ),
    ]
