# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0011_auto_20180915_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletterparagraph',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
