# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-23 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0012_auto_20180916_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('fileType', models.CharField(choices=[('resume', 'Resume'), ('image', 'Image'), ('other', 'other')], max_length=100)),
                ('file', models.FileField(upload_to=models.CharField(choices=[('resume', 'Resume'), ('image', 'Image'), ('other', 'other')], max_length=100))),
            ],
        ),
    ]
