# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-23 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0013_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='fileName',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='fileType',
            new_name='file_type',
        ),
    ]
