# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0014_auto_20180923_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=models.CharField(choices=[('resume', 'Resume'), ('image', 'Image'), ('other', 'Other')], max_length=100)),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('image', 'Image'), ('other', 'Other')], max_length=100),
        ),
    ]
