# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 00:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0015_auto_20180924_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 0, 40, 48, 928311, tzinfo=utc)),
        ),
    ]
