# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0016_media_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
